[package]
authors = ["KirmesBude <kirmesbude@gmail.com>"]
name = "bevy_trickfilm"
version = "0.4.0"
edition = "2021"
description = "Bevy plugin for spritesheet manifest loading"
repository = "https://github.com/KirmesBude/bevy_trickfilm"
license = "MIT OR Apache-2.0"
keywords = ["gamedev", "bevy", "animation", "spritesheet", "assets"]
categories = ["game-development"]
readme = "README.md"
exclude = ["/assets"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12", default-features = false, features=["bevy_asset", "bevy_render", "bevy_sprite"]}
serde = { version = "1", features = ["derive"] }
ron = "0.8"
thiserror = "1"

[dev-dependencies]
bevy = "0.12"
bevy_titan = "0.4"

[[example]]
name = "spritesheet_animation_titan"
path = "examples/spritesheet_animation_titan.rs"

[[example]]
name = "spritesheet_animation"
path = "examples/spritesheet_animation.rs"
